// =============================================================================
// src/lib/resto-mock-data.ts — Datos de demostración para el módulo de sala
// =============================================================================
// Mock data para mesas, turnos, reservas y pedidos.
// Las fechas se calculan dinámicamente para que siempre parezcan actuales.
// =============================================================================

import type {
  Table,
  Turn,
  Reservation,
} from "@/features/reservations/schemas/reservation.schema"

// ─── Tipos locales (los schemas llegarán en una sesión posterior) ────────────

export interface OrderLine {
  id: string
  recipe_id: string
  recipe_name: string
  quantity: number
  unit_price: number
  modifiers?: string[]
  status: "pending" | "preparing" | "ready" | "served"
  sent_to_kitchen_at?: string
}

export interface Order {
  id: string
  hotel_id: string
  table_id?: string
  waiter_id?: string
  status: "open" | "kitchen" | "served" | "paid" | "cancelled"
  lines: OrderLine[]
  subtotal: number
  tax_pct: number
  total: number
  payment_method?: "cash" | "card" | "split"
  opened_at: string
  closed_at?: string
  notes?: string
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function dateOffset(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

function todayAt(hh: string, mm: string): string {
  const d = new Date()
  return `${d.toISOString().slice(0, 10)}T${hh}:${mm}:00`
}

const R1 = "r1"

// ─── MOCK_TABLES (12 mesas) ─────────────────────────────────────────────────

export const MOCK_TABLES: Table[] = [
  // Sala principal
  { id: "t1",  hotel_id: R1, name: "Mesa 1",    zone: "sala",    capacity: 4,  is_active: true, position_x: 100, position_y: 100 },
  { id: "t2",  hotel_id: R1, name: "Mesa 2",    zone: "sala",    capacity: 2,  is_active: true, position_x: 250, position_y: 100 },
  { id: "t3",  hotel_id: R1, name: "Mesa 3",    zone: "sala",    capacity: 4,  is_active: true, position_x: 400, position_y: 100 },
  { id: "t4",  hotel_id: R1, name: "Mesa 4",    zone: "sala",    capacity: 6,  is_active: true, position_x: 100, position_y: 250 },
  { id: "t5",  hotel_id: R1, name: "Mesa 5",    zone: "sala",    capacity: 2,  is_active: true, position_x: 250, position_y: 250 },
  { id: "t6",  hotel_id: R1, name: "Mesa 6",    zone: "sala",    capacity: 4,  is_active: true, position_x: 400, position_y: 250 },
  { id: "t7",  hotel_id: R1, name: "Mesa 7",    zone: "sala",    capacity: 8,  is_active: true, position_x: 100, position_y: 400 },
  { id: "t8",  hotel_id: R1, name: "Mesa 8",    zone: "sala",    capacity: 4,  is_active: true, position_x: 250, position_y: 400 },
  // Terraza
  { id: "t9",  hotel_id: R1, name: "Terraza 1", zone: "terraza", capacity: 6,  is_active: true, position_x: 600, position_y: 100 },
  { id: "t10", hotel_id: R1, name: "Terraza 2", zone: "terraza", capacity: 4,  is_active: true, position_x: 600, position_y: 250 },
  // Barra
  { id: "t11", hotel_id: R1, name: "Barra 1",   zone: "barra",   capacity: 2,  is_active: true, position_x: 50,  position_y: 500 },
  // Privado
  { id: "t12", hotel_id: R1, name: "Privado",   zone: "privado", capacity: 12, is_active: true, position_x: 500, position_y: 400 },
]

// ─── MOCK_TURNS (2 turnos) ──────────────────────────────────────────────────

export const MOCK_TURNS: Turn[] = [
  {
    id: "turn-1",
    name: "Comida",
    start_time: "13:00",
    end_time: "16:00",
    days: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    id: "turn-2",
    name: "Cena",
    start_time: "20:00",
    end_time: "23:30",
    days: [1, 2, 3, 4, 5, 6],
  },
]

// ─── MOCK_RESERVATIONS (30 reservas) ────────────────────────────────────────

export const MOCK_RESERVATIONS: Reservation[] = [
  // ── Hoy — Comida ──────────────────────────────────────────────────────────
  {
    id: "res-01",
    hotel_id: R1,
    table_id: "t1",
    date: dateOffset(0),
    time: "13:00",
    pax: 4,
    customer_name: "García López",
    customer_phone: "+34 612 345 678",
    customer_email: "garcia.lopez@email.es",
    status: "confirmed",
    source: "phone",
    notes: "Alergia a frutos secos",
    is_vip: false,
    created_at: todayAt("09", "15"),
  },
  {
    id: "res-02",
    hotel_id: R1,
    table_id: "t4",
    date: dateOffset(0),
    time: "13:30",
    pax: 6,
    customer_name: "Martínez Ruiz",
    customer_phone: "+34 623 456 789",
    status: "seated",
    source: "web",
    is_vip: true,
    notes: "Cliente habitual — prefiere mesa junto a la ventana",
    created_at: todayAt("08", "00"),
  },
  {
    id: "res-03",
    hotel_id: R1,
    table_id: "t2",
    date: dateOffset(0),
    time: "14:00",
    pax: 2,
    customer_name: "Hernández Moreno",
    customer_phone: "+34 634 567 890",
    status: "confirmed",
    source: "thefork",
    is_vip: false,
    created_at: todayAt("10", "30"),
  },
  {
    id: "res-04",
    hotel_id: R1,
    table_id: "t7",
    date: dateOffset(0),
    time: "14:00",
    pax: 8,
    customer_name: "Fernández Díaz",
    customer_phone: "+34 645 678 901",
    status: "confirmed",
    source: "phone",
    notes: "Cumpleaños — preparar tarta",
    is_vip: false,
    created_at: todayAt("11", "00"),
  },
  {
    id: "res-05",
    hotel_id: R1,
    table_id: "t9",
    date: dateOffset(0),
    time: "13:30",
    pax: 5,
    customer_name: "Sánchez Navarro",
    customer_phone: "+34 656 789 012",
    status: "pending",
    source: "app",
    is_vip: false,
    created_at: todayAt("12", "00"),
  },

  // ── Hoy — Cena ────────────────────────────────────────────────────────────
  {
    id: "res-06",
    hotel_id: R1,
    table_id: "t3",
    date: dateOffset(0),
    time: "20:30",
    pax: 4,
    customer_name: "López Serrano",
    customer_phone: "+34 667 890 123",
    status: "confirmed",
    source: "web",
    is_vip: false,
    created_at: todayAt("14", "00"),
  },
  {
    id: "res-07",
    hotel_id: R1,
    table_id: "t12",
    date: dateOffset(0),
    time: "21:00",
    pax: 10,
    customer_name: "Rodríguez Blanco",
    customer_phone: "+34 678 901 234",
    customer_email: "rodriguez.blanco@empresa.com",
    status: "confirmed",
    source: "phone",
    notes: "Cena de empresa — menú cerrado",
    is_vip: true,
    created_at: todayAt("09", "45"),
  },
  {
    id: "res-08",
    hotel_id: R1,
    table_id: "t5",
    date: dateOffset(0),
    time: "20:00",
    pax: 2,
    customer_name: "Jiménez Torres",
    customer_phone: "+34 689 012 345",
    status: "pending",
    source: "thefork",
    is_vip: false,
    created_at: todayAt("16", "30"),
  },
  {
    id: "res-09",
    hotel_id: R1,
    table_id: "t6",
    date: dateOffset(0),
    time: "21:30",
    pax: 3,
    customer_name: "Alonso Vega",
    customer_phone: "+34 690 123 456",
    status: "confirmed",
    source: "walk_in",
    is_vip: false,
    created_at: todayAt("17", "00"),
  },
  {
    id: "res-10",
    hotel_id: R1,
    table_id: "t10",
    date: dateOffset(0),
    time: "20:30",
    pax: 4,
    customer_name: "Ramírez Castro",
    customer_phone: "+34 601 234 567",
    status: "no_show",
    source: "web",
    is_vip: false,
    created_at: todayAt("10", "00"),
  },

  // ── Mañana (+1) ───────────────────────────────────────────────────────────
  {
    id: "res-11",
    hotel_id: R1,
    table_id: "t1",
    date: dateOffset(1),
    time: "13:30",
    pax: 3,
    customer_name: "Muñoz Herrera",
    customer_phone: "+34 612 345 001",
    status: "confirmed",
    source: "phone",
    is_vip: false,
    created_at: todayAt("08", "30"),
  },
  {
    id: "res-12",
    hotel_id: R1,
    table_id: "t3",
    date: dateOffset(1),
    time: "14:00",
    pax: 4,
    customer_name: "Romero Iglesias",
    customer_phone: "+34 623 456 002",
    status: "pending",
    source: "app",
    is_vip: false,
    created_at: todayAt("11", "15"),
  },
  {
    id: "res-13",
    hotel_id: R1,
    table_id: "t4",
    date: dateOffset(1),
    time: "21:00",
    pax: 6,
    customer_name: "Navarro Ortega",
    customer_phone: "+34 634 567 003",
    customer_email: "navarro.ortega@gmail.com",
    status: "confirmed",
    source: "web",
    notes: "Mesa tranquila, lejos de la cocina",
    is_vip: true,
    created_at: todayAt("09", "00"),
  },
  {
    id: "res-14",
    hotel_id: R1,
    table_id: "t8",
    date: dateOffset(1),
    time: "20:30",
    pax: 4,
    customer_name: "Torres Medina",
    customer_phone: "+34 645 678 004",
    status: "confirmed",
    source: "thefork",
    is_vip: false,
    created_at: todayAt("13", "00"),
  },

  // ── Pasado mañana (+2) ────────────────────────────────────────────────────
  {
    id: "res-15",
    hotel_id: R1,
    table_id: "t9",
    date: dateOffset(2),
    time: "13:00",
    pax: 5,
    customer_name: "Domínguez Peña",
    customer_phone: "+34 656 789 005",
    status: "confirmed",
    source: "phone",
    is_vip: false,
    created_at: todayAt("10", "45"),
  },
  {
    id: "res-16",
    hotel_id: R1,
    table_id: "t2",
    date: dateOffset(2),
    time: "22:00",
    pax: 2,
    customer_name: "Vázquez Prieto",
    customer_phone: "+34 667 890 006",
    status: "pending",
    source: "app",
    is_vip: false,
    created_at: todayAt("15", "20"),
  },
  {
    id: "res-17",
    hotel_id: R1,
    table_id: "t7",
    date: dateOffset(2),
    time: "14:30",
    pax: 7,
    customer_name: "Ramos Fuentes",
    customer_phone: "+34 678 901 007",
    status: "confirmed",
    source: "web",
    notes: "2 celíacos en el grupo",
    is_vip: false,
    created_at: todayAt("08", "15"),
  },

  // ── +3 días ───────────────────────────────────────────────────────────────
  {
    id: "res-18",
    hotel_id: R1,
    table_id: "t6",
    date: dateOffset(3),
    time: "13:00",
    pax: 4,
    customer_name: "Gil Rubio",
    customer_phone: "+34 689 012 008",
    status: "confirmed",
    source: "phone",
    is_vip: false,
    created_at: todayAt("11", "30"),
  },
  {
    id: "res-19",
    hotel_id: R1,
    table_id: "t12",
    date: dateOffset(3),
    time: "21:00",
    pax: 12,
    customer_name: "Morales Guerrero",
    customer_phone: "+34 690 123 009",
    customer_email: "morales@bufete.es",
    status: "confirmed",
    source: "phone",
    notes: "Aniversario de empresa — cava a la llegada",
    is_vip: true,
    created_at: todayAt("09", "30"),
  },
  {
    id: "res-20",
    hotel_id: R1,
    table_id: undefined,
    date: dateOffset(3),
    time: "14:00",
    pax: 2,
    customer_name: "Ortega Campos",
    customer_phone: "+34 601 234 010",
    status: "pending",
    source: "walk_in",
    is_vip: false,
    created_at: todayAt("12", "00"),
  },

  // ── +4 días ───────────────────────────────────────────────────────────────
  {
    id: "res-21",
    hotel_id: R1,
    table_id: "t5",
    date: dateOffset(4),
    time: "13:30",
    pax: 2,
    customer_name: "Castillo Reyes",
    customer_phone: "+34 612 345 011",
    status: "confirmed",
    source: "thefork",
    is_vip: false,
    created_at: todayAt("14", "00"),
  },
  {
    id: "res-22",
    hotel_id: R1,
    table_id: "t3",
    date: dateOffset(4),
    time: "20:00",
    pax: 4,
    customer_name: "Santos León",
    customer_phone: "+34 623 456 012",
    status: "confirmed",
    source: "web",
    is_vip: false,
    created_at: todayAt("10", "30"),
  },
  {
    id: "res-23",
    hotel_id: R1,
    table_id: "t10",
    date: dateOffset(4),
    time: "15:00",
    pax: 3,
    customer_name: "Delgado Marin",
    customer_phone: "+34 634 567 013",
    status: "cancelled",
    source: "app",
    notes: "Cancelado por el cliente",
    is_vip: false,
    created_at: todayAt("09", "00"),
  },

  // ── +5 días ───────────────────────────────────────────────────────────────
  {
    id: "res-24",
    hotel_id: R1,
    table_id: "t1",
    date: dateOffset(5),
    time: "21:30",
    pax: 4,
    customer_name: "Méndez Soto",
    customer_phone: "+34 645 678 014",
    status: "pending",
    source: "phone",
    is_vip: false,
    created_at: todayAt("16", "00"),
  },
  {
    id: "res-25",
    hotel_id: R1,
    table_id: "t4",
    date: dateOffset(5),
    time: "13:00",
    pax: 6,
    customer_name: "Vargas Molina",
    customer_phone: "+34 656 789 015",
    customer_email: "vargas.molina@outlook.es",
    status: "confirmed",
    source: "web",
    is_vip: true,
    notes: "Celebración familiar",
    created_at: todayAt("07", "45"),
  },

  // ── +6 días ───────────────────────────────────────────────────────────────
  {
    id: "res-26",
    hotel_id: R1,
    table_id: "t11",
    date: dateOffset(6),
    time: "14:00",
    pax: 1,
    customer_name: "Peña Aguilar",
    customer_phone: "+34 667 890 016",
    status: "confirmed",
    source: "walk_in",
    is_vip: false,
    created_at: todayAt("12", "15"),
  },
  {
    id: "res-27",
    hotel_id: R1,
    table_id: "t9",
    date: dateOffset(6),
    time: "20:30",
    pax: 5,
    customer_name: "Cabrera Flores",
    customer_phone: "+34 678 901 017",
    status: "pending",
    source: "thefork",
    is_vip: false,
    created_at: todayAt("11", "00"),
  },

  // ── +7 días ───────────────────────────────────────────────────────────────
  {
    id: "res-28",
    hotel_id: R1,
    table_id: "t7",
    date: dateOffset(7),
    time: "13:00",
    pax: 8,
    customer_name: "Crespo Gallardo",
    customer_phone: "+34 689 012 018",
    status: "confirmed",
    source: "phone",
    notes: "Comida de negocios — factura a nombre de empresa",
    is_vip: true,
    created_at: todayAt("08", "00"),
  },
  {
    id: "res-29",
    hotel_id: R1,
    table_id: undefined,
    date: dateOffset(7),
    time: "22:00",
    pax: 2,
    customer_name: "Pardo Caballero",
    customer_phone: "+34 690 123 019",
    status: "pending",
    source: "app",
    is_vip: false,
    created_at: todayAt("17", "30"),
  },
  {
    id: "res-30",
    hotel_id: R1,
    table_id: "t8",
    date: dateOffset(7),
    time: "14:30",
    pax: 4,
    customer_name: "Ibáñez Calvo",
    customer_phone: "+34 601 234 020",
    status: "completed",
    source: "web",
    is_vip: false,
    created_at: todayAt("10", "00"),
  },
]

// ─── MOCK_ORDERS (20 pedidos) ───────────────────────────────────────────────

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-01",
    hotel_id: R1,
    table_id: "t1",
    waiter_id: "w1",
    status: "paid",
    lines: [
      { id: "ol-0101", recipe_id: "rec-01", recipe_name: "Croquetas de jamón", quantity: 2, unit_price: 9.50, status: "served" },
      { id: "ol-0102", recipe_id: "rec-10", recipe_name: "Solomillo a la pimienta", quantity: 2, unit_price: 22.00, status: "served" },
      { id: "ol-0103", recipe_id: "rec-20", recipe_name: "Tarta de queso", quantity: 2, unit_price: 7.50, status: "served" },
    ],
    subtotal: 78.00,
    tax_pct: 10,
    total: 85.80,
    payment_method: "card",
    opened_at: todayAt("13", "10"),
    closed_at: todayAt("14", "45"),
  },
  {
    id: "ord-02",
    hotel_id: R1,
    table_id: "t2",
    waiter_id: "w2",
    status: "paid",
    lines: [
      { id: "ol-0201", recipe_id: "rec-02", recipe_name: "Ensalada mixta", quantity: 1, unit_price: 8.00, status: "served" },
      { id: "ol-0202", recipe_id: "rec-12", recipe_name: "Lubina a la sal", quantity: 1, unit_price: 24.00, status: "served" },
      { id: "ol-0203", recipe_id: "rec-03", recipe_name: "Gazpacho", quantity: 1, unit_price: 6.50, status: "served" },
    ],
    subtotal: 38.50,
    tax_pct: 10,
    total: 42.35,
    payment_method: "cash",
    opened_at: todayAt("13", "25"),
    closed_at: todayAt("14", "50"),
  },
  {
    id: "ord-03",
    hotel_id: R1,
    table_id: "t4",
    waiter_id: "w1",
    status: "served",
    lines: [
      { id: "ol-0301", recipe_id: "rec-04", recipe_name: "Patatas bravas", quantity: 2, unit_price: 7.00, status: "served" },
      { id: "ol-0302", recipe_id: "rec-05", recipe_name: "Tortilla española", quantity: 1, unit_price: 9.00, status: "served" },
      { id: "ol-0303", recipe_id: "rec-11", recipe_name: "Arroz negro", quantity: 3, unit_price: 16.50, status: "served" },
      { id: "ol-0304", recipe_id: "rec-21", recipe_name: "Crema catalana", quantity: 3, unit_price: 6.00, status: "served" },
    ],
    subtotal: 90.50,
    tax_pct: 10,
    total: 99.55,
    opened_at: todayAt("13", "35"),
  },
  {
    id: "ord-04",
    hotel_id: R1,
    table_id: "t3",
    waiter_id: "w2",
    status: "kitchen",
    lines: [
      { id: "ol-0401", recipe_id: "rec-06", recipe_name: "Jamón ibérico", quantity: 1, unit_price: 18.00, status: "served", sent_to_kitchen_at: todayAt("13", "45") },
      { id: "ol-0402", recipe_id: "rec-13", recipe_name: "Entrecot de ternera", quantity: 2, unit_price: 23.00, modifiers: ["Poco hecho", "Al punto"], status: "preparing", sent_to_kitchen_at: todayAt("14", "00") },
      { id: "ol-0403", recipe_id: "rec-07", recipe_name: "Ensaladilla rusa", quantity: 1, unit_price: 8.50, status: "served", sent_to_kitchen_at: todayAt("13", "45") },
    ],
    subtotal: 72.50,
    tax_pct: 10,
    total: 79.75,
    opened_at: todayAt("13", "40"),
  },
  {
    id: "ord-05",
    hotel_id: R1,
    table_id: "t7",
    waiter_id: "w3",
    status: "kitchen",
    lines: [
      { id: "ol-0501", recipe_id: "rec-01", recipe_name: "Croquetas de jamón", quantity: 3, unit_price: 9.50, status: "served", sent_to_kitchen_at: todayAt("14", "05") },
      { id: "ol-0502", recipe_id: "rec-08", recipe_name: "Gambas al ajillo", quantity: 2, unit_price: 14.00, status: "ready", sent_to_kitchen_at: todayAt("14", "05") },
      { id: "ol-0503", recipe_id: "rec-14", recipe_name: "Paella valenciana", quantity: 4, unit_price: 18.00, status: "preparing", sent_to_kitchen_at: todayAt("14", "15") },
      { id: "ol-0504", recipe_id: "rec-15", recipe_name: "Secreto ibérico", quantity: 2, unit_price: 19.50, status: "preparing", sent_to_kitchen_at: todayAt("14", "15") },
    ],
    subtotal: 166.50,
    tax_pct: 10,
    total: 183.15,
    opened_at: todayAt("14", "00"),
    notes: "Mesa de cumpleaños — llevar tarta al final",
  },
  {
    id: "ord-06",
    hotel_id: R1,
    table_id: "t9",
    waiter_id: "w1",
    status: "open",
    lines: [
      { id: "ol-0601", recipe_id: "rec-09", recipe_name: "Pulpo a la gallega", quantity: 2, unit_price: 16.00, status: "pending" },
      { id: "ol-0602", recipe_id: "rec-02", recipe_name: "Ensalada mixta", quantity: 1, unit_price: 8.00, status: "pending" },
    ],
    subtotal: 40.00,
    tax_pct: 10,
    total: 44.00,
    opened_at: todayAt("13", "50"),
  },
  {
    id: "ord-07",
    hotel_id: R1,
    table_id: "t5",
    waiter_id: "w2",
    status: "paid",
    lines: [
      { id: "ol-0701", recipe_id: "rec-03", recipe_name: "Gazpacho", quantity: 2, unit_price: 6.50, status: "served" },
      { id: "ol-0702", recipe_id: "rec-16", recipe_name: "Merluza en salsa verde", quantity: 2, unit_price: 17.00, status: "served" },
    ],
    subtotal: 47.00,
    tax_pct: 10,
    total: 51.70,
    payment_method: "card",
    opened_at: todayAt("13", "15"),
    closed_at: todayAt("14", "30"),
  },
  {
    id: "ord-08",
    hotel_id: R1,
    table_id: "t6",
    waiter_id: "w3",
    status: "served",
    lines: [
      { id: "ol-0801", recipe_id: "rec-04", recipe_name: "Patatas bravas", quantity: 1, unit_price: 7.00, status: "served" },
      { id: "ol-0802", recipe_id: "rec-17", recipe_name: "Chuletas de cordero", quantity: 2, unit_price: 21.00, status: "served" },
      { id: "ol-0803", recipe_id: "rec-22", recipe_name: "Flan casero", quantity: 2, unit_price: 5.50, status: "served" },
    ],
    subtotal: 60.00,
    tax_pct: 10,
    total: 66.00,
    opened_at: todayAt("13", "20"),
  },
  {
    id: "ord-09",
    hotel_id: R1,
    table_id: "t10",
    waiter_id: "w1",
    status: "paid",
    lines: [
      { id: "ol-0901", recipe_id: "rec-06", recipe_name: "Jamón ibérico", quantity: 1, unit_price: 18.00, status: "served" },
      { id: "ol-0902", recipe_id: "rec-05", recipe_name: "Tortilla española", quantity: 1, unit_price: 9.00, status: "served" },
      { id: "ol-0903", recipe_id: "rec-18", recipe_name: "Cochinillo asado", quantity: 2, unit_price: 25.00, status: "served" },
      { id: "ol-0904", recipe_id: "rec-20", recipe_name: "Tarta de queso", quantity: 2, unit_price: 7.50, status: "served" },
    ],
    subtotal: 92.00,
    tax_pct: 10,
    total: 101.20,
    payment_method: "split",
    opened_at: todayAt("13", "00"),
    closed_at: todayAt("15", "10"),
  },
  {
    id: "ord-10",
    hotel_id: R1,
    table_id: "t8",
    waiter_id: "w2",
    status: "kitchen",
    lines: [
      { id: "ol-1001", recipe_id: "rec-08", recipe_name: "Gambas al ajillo", quantity: 1, unit_price: 14.00, status: "served", sent_to_kitchen_at: todayAt("14", "10") },
      { id: "ol-1002", recipe_id: "rec-19", recipe_name: "Rape a la marinera", quantity: 2, unit_price: 20.00, status: "preparing", sent_to_kitchen_at: todayAt("14", "25") },
    ],
    subtotal: 54.00,
    tax_pct: 10,
    total: 59.40,
    opened_at: todayAt("14", "05"),
  },
  {
    id: "ord-11",
    hotel_id: R1,
    table_id: "t11",
    waiter_id: "w3",
    status: "paid",
    lines: [
      { id: "ol-1101", recipe_id: "rec-04", recipe_name: "Patatas bravas", quantity: 1, unit_price: 7.00, status: "served" },
      { id: "ol-1102", recipe_id: "rec-01", recipe_name: "Croquetas de jamón", quantity: 1, unit_price: 9.50, status: "served" },
    ],
    subtotal: 16.50,
    tax_pct: 10,
    total: 18.15,
    payment_method: "cash",
    opened_at: todayAt("13", "05"),
    closed_at: todayAt("13", "50"),
  },
  {
    id: "ord-12",
    hotel_id: R1,
    table_id: "t12",
    waiter_id: "w1",
    status: "served",
    lines: [
      { id: "ol-1201", recipe_id: "rec-09", recipe_name: "Pulpo a la gallega", quantity: 3, unit_price: 16.00, status: "served" },
      { id: "ol-1202", recipe_id: "rec-06", recipe_name: "Jamón ibérico", quantity: 2, unit_price: 18.00, status: "served" },
      { id: "ol-1203", recipe_id: "rec-10", recipe_name: "Solomillo a la pimienta", quantity: 5, unit_price: 22.00, status: "served" },
      { id: "ol-1204", recipe_id: "rec-18", recipe_name: "Cochinillo asado", quantity: 3, unit_price: 25.00, status: "served" },
      { id: "ol-1205", recipe_id: "rec-21", recipe_name: "Crema catalana", quantity: 5, unit_price: 6.00, status: "served" },
    ],
    subtotal: 289.00,
    tax_pct: 10,
    total: 317.90,
    opened_at: todayAt("13", "30"),
    notes: "Cena de empresa — menú cerrado",
  },
  {
    id: "ord-13",
    hotel_id: R1,
    table_id: "t1",
    waiter_id: "w2",
    status: "open",
    lines: [
      { id: "ol-1301", recipe_id: "rec-07", recipe_name: "Ensaladilla rusa", quantity: 1, unit_price: 8.50, status: "pending" },
      { id: "ol-1302", recipe_id: "rec-03", recipe_name: "Gazpacho", quantity: 1, unit_price: 6.50, status: "pending" },
    ],
    subtotal: 15.00,
    tax_pct: 10,
    total: 16.50,
    opened_at: todayAt("20", "05"),
  },
  {
    id: "ord-14",
    hotel_id: R1,
    table_id: "t3",
    waiter_id: "w3",
    status: "kitchen",
    lines: [
      { id: "ol-1401", recipe_id: "rec-01", recipe_name: "Croquetas de jamón", quantity: 2, unit_price: 9.50, status: "ready", sent_to_kitchen_at: todayAt("20", "15") },
      { id: "ol-1402", recipe_id: "rec-15", recipe_name: "Secreto ibérico", quantity: 2, unit_price: 19.50, modifiers: ["Al punto"], status: "preparing", sent_to_kitchen_at: todayAt("20", "25") },
      { id: "ol-1403", recipe_id: "rec-12", recipe_name: "Lubina a la sal", quantity: 1, unit_price: 24.00, status: "preparing", sent_to_kitchen_at: todayAt("20", "25") },
    ],
    subtotal: 82.50,
    tax_pct: 10,
    total: 90.75,
    opened_at: todayAt("20", "10"),
  },
  {
    id: "ord-15",
    hotel_id: R1,
    table_id: "t5",
    waiter_id: "w1",
    status: "open",
    lines: [
      { id: "ol-1501", recipe_id: "rec-02", recipe_name: "Ensalada mixta", quantity: 2, unit_price: 8.00, status: "pending" },
    ],
    subtotal: 16.00,
    tax_pct: 10,
    total: 17.60,
    opened_at: todayAt("20", "00"),
  },
  {
    id: "ord-16",
    hotel_id: R1,
    table_id: "t6",
    waiter_id: "w2",
    status: "kitchen",
    lines: [
      { id: "ol-1601", recipe_id: "rec-08", recipe_name: "Gambas al ajillo", quantity: 1, unit_price: 14.00, status: "served", sent_to_kitchen_at: todayAt("21", "05") },
      { id: "ol-1602", recipe_id: "rec-13", recipe_name: "Entrecot de ternera", quantity: 1, unit_price: 23.00, modifiers: ["Muy hecho"], status: "preparing", sent_to_kitchen_at: todayAt("21", "15") },
      { id: "ol-1603", recipe_id: "rec-14", recipe_name: "Paella valenciana", quantity: 1, unit_price: 18.00, status: "preparing", sent_to_kitchen_at: todayAt("21", "15") },
    ],
    subtotal: 55.00,
    tax_pct: 10,
    total: 60.50,
    opened_at: todayAt("21", "00"),
  },
  {
    id: "ord-17",
    hotel_id: R1,
    table_id: "t9",
    waiter_id: "w3",
    status: "served",
    lines: [
      { id: "ol-1701", recipe_id: "rec-04", recipe_name: "Patatas bravas", quantity: 2, unit_price: 7.00, status: "served" },
      { id: "ol-1702", recipe_id: "rec-09", recipe_name: "Pulpo a la gallega", quantity: 2, unit_price: 16.00, status: "served" },
      { id: "ol-1703", recipe_id: "rec-16", recipe_name: "Merluza en salsa verde", quantity: 2, unit_price: 17.00, status: "served" },
      { id: "ol-1704", recipe_id: "rec-22", recipe_name: "Flan casero", quantity: 2, unit_price: 5.50, status: "served" },
    ],
    subtotal: 91.00,
    tax_pct: 10,
    total: 100.10,
    opened_at: todayAt("20", "15"),
  },
  {
    id: "ord-18",
    hotel_id: R1,
    table_id: "t4",
    waiter_id: "w1",
    status: "open",
    lines: [
      { id: "ol-1801", recipe_id: "rec-06", recipe_name: "Jamón ibérico", quantity: 1, unit_price: 18.00, status: "pending" },
      { id: "ol-1802", recipe_id: "rec-05", recipe_name: "Tortilla española", quantity: 1, unit_price: 9.00, status: "pending" },
      { id: "ol-1803", recipe_id: "rec-07", recipe_name: "Ensaladilla rusa", quantity: 1, unit_price: 8.50, status: "pending" },
    ],
    subtotal: 35.50,
    tax_pct: 10,
    total: 39.05,
    opened_at: todayAt("20", "30"),
  },
  {
    id: "ord-19",
    hotel_id: R1,
    table_id: "t10",
    waiter_id: "w2",
    status: "paid",
    lines: [
      { id: "ol-1901", recipe_id: "rec-03", recipe_name: "Gazpacho", quantity: 2, unit_price: 6.50, status: "served" },
      { id: "ol-1902", recipe_id: "rec-17", recipe_name: "Chuletas de cordero", quantity: 2, unit_price: 21.00, status: "served" },
      { id: "ol-1903", recipe_id: "rec-20", recipe_name: "Tarta de queso", quantity: 1, unit_price: 7.50, status: "served" },
    ],
    subtotal: 62.50,
    tax_pct: 10,
    total: 68.75,
    payment_method: "card",
    opened_at: todayAt("20", "00"),
    closed_at: todayAt("21", "45"),
  },
  {
    id: "ord-20",
    hotel_id: R1,
    table_id: "t8",
    waiter_id: "w3",
    status: "kitchen",
    lines: [
      { id: "ol-2001", recipe_id: "rec-01", recipe_name: "Croquetas de jamón", quantity: 1, unit_price: 9.50, status: "served", sent_to_kitchen_at: todayAt("20", "40") },
      { id: "ol-2002", recipe_id: "rec-11", recipe_name: "Arroz negro", quantity: 2, unit_price: 16.50, status: "preparing", sent_to_kitchen_at: todayAt("20", "50") },
      { id: "ol-2003", recipe_id: "rec-19", recipe_name: "Rape a la marinera", quantity: 1, unit_price: 20.00, status: "pending" },
    ],
    subtotal: 62.50,
    tax_pct: 10,
    total: 68.75,
    opened_at: todayAt("20", "35"),
  },
]
